# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: fslabs test aws cicd

on:
  push:
    branches: main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: nodejs config
      uses: actions/setup-node@v4
      with:
        node-version: 15
        cache: 'npm'
        cache-dapendency-path: codebase\rdicidr-0.1.0\package-lock.json

    - name: install
      working-directory: codebase\rdicidr-0.1.0
      run: npm install 

    - name: lint
      working-directory: codebase\rdicidr-0.1.0
      run: npm run lint
      
    - name: prettier
      working-directory: codebase\rdicidr-0.1.0
      run: npm run prettier || true 
      
    - name: test
      working-directory: codebase\rdicidr-0.1.0
      run: CI=true npm run test

    - name: test
      working-directory: codebase\rdicidr-0.1.0
      run: npm run build

  buildimage:

    runs-on: ubuntu-latest
    needs: [build]

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: Build the Docker image
      working-directory: codebase\rdicidr-0.1.0
      run: |
        echo "${{secrets.GHCR_TOKEN}}" | docker login ghcr.io -u daniel55247 --password-stdin
        docker build -t ghcr.io/daniel55247/awschallenge/awschallengeimage:latest . 
        docker push ghcr.io/daniel55247/awschallenge/awschallengeimage:latest

    

    